"""make_system_prompt_required

Revision ID: e8601e17610e
Revises: f7700fe29859
Create Date: 2025-08-27 20:06:50.736109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8601e17610e'
down_revision: Union[str, None] = 'f7700fe29859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First, update any existing NULL values with a default system prompt
    op.execute("""
        UPDATE connections 
        SET system_prompt = 'This is a database connection. Please help users query the data effectively by generating accurate SQL queries and providing clear explanations of the results.'
        WHERE system_prompt IS NULL OR system_prompt = ''
    """)
    
    # Then make the column NOT NULL
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.alter_column('system_prompt',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.alter_column('system_prompt',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
